# Generated by Django 6.0.4 on 2026-04-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_class', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('github_link', models.URLField(blank=True)),
                ('deploy_link', models.URLField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('technologies', models.ManyToManyField(blank=True, to='core.technology')),
            ],
        ),
    ]
