# Generated by Django 6.0.4 on 2026-05-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='icon',
        ),
        migrations.AddField(
            model_name='technology',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='technologies/'),
        ),
    ]
