# Generated by Django 6.0.4 on 2026-05-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_course_icon_technology_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
