# Generated by Django 6.0.4 on 2026-05-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_course_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='conclusion_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='platform',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='gif',
            field=models.FileField(blank=True, null=True, upload_to='projects/gifs/'),
        ),
    ]
