# Generated by Django 6.0.4 on 2026-05-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_conclusion_date_course_platform_project_gif'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
