from django import template

register = template.Library()

DEVICON_MAP = {
    "python": "python",
    "django": "django",
    "flask": "flask",
    "fastapi": "fastapi",
    "c#": "csharp",
    "csharp": "csharp",
    "asp.net": "dotnetcore",
    "asp.net core": "dotnetcore",
    ".net": "dotnetcore",
    "dotnet": "dotnetcore",
    "sql": "postgresql",
    "mysql": "mysql",
    "postgresql": "postgresql",
    "sqlite": "sqlite",
    "mongodb": "mongodb",
    "git": "git",
    "github": "github",
    "gitlab": "gitlab",
    "docker": "docker",
    "kubernetes": "kubernetes",
    "linux": "linux",
    "ubuntu": "ubuntu",
    "html": "html5",
    "html5": "html5",
    "css": "css3",
    "css3": "css3",
    "javascript": "javascript",
    "js": "javascript",
    "typescript": "typescript",
    "ts": "typescript",
    "node": "nodejs",
    "node.js": "nodejs",
    "nodejs": "nodejs",
    "react": "react",
    "angular": "angular",
    "vue": "vuejs",
    "vue.js": "vuejs",
    "sass": "sass",
    "less": "less",
    "tailwind": "tailwindcss",
    "bootstrap": "bootstrap",
    "jquery": "jquery",
    "webpack": "webpack",
    "vscode": "vscode",
    "visual studio": "visualstudio",
    "figma": "figma",
    "photoshop": "photoshop",
    "aws": "amazonwebservices",
    "azure": "azure",
    "gcp": "googlecloud",
    "google cloud": "googlecloud",
    "redis": "redis",
    "nginx": "nginx",
    "apache": "apache",
    "bash": "bash",
    "powershell": "powershell",
    "java": "java",
    "go": "go",
    "golang": "go",
    "rust": "rust",
    "ruby": "ruby",
    "php": "php",
    "swift": "swift",
    "kotlin": "kotlin",
    "terraform": "terraform",
    "ansible": "ansible",
    "grafana": "grafana",
    "prometheus": "prometheus",
    "jest": "jest",
    "pytest": "pytest",
}

@register.filter
def devicon_name(value):
    name = value.strip().lower()
    if name in DEVICON_MAP:
        return DEVICON_MAP[name]
    return name.replace(" ", "").replace(".", "").replace("#", "sharp")
